require("../../../../psknode/bundles/testsRuntime");
const assert = require("double-check").assert;
const PasswordSSI = require("../../lib/KeySSIs/ConstSSIs/PasswordSSI");
const ConstSSI = require("../../lib/KeySSIs/ConstSSIs/ConstSSI");
const CZaSSI = require("../../lib/KeySSIs/ConstSSIs/CZaSSI");
const passwordSSI = PasswordSSI.createPasswordSSI();
passwordSSI.initialize("domain", "user", "password", 2000, "v0");
assert.begin();
const constSSI = passwordSSI.derive();
assert.true(constSSI.constructor.name === ConstSSI.createConstSSI().constructor.name);
const cZaSSI = constSSI.derive();
assert.true(cZaSSI.constructor.name === CZaSSI.createCZaSSI().constructor.name);
assert.end();